Version 0.5.120


```
05:14:19.540- |apero_processing| 
05:14:19.551- |apero_processing| 
05:14:19.561- |apero_processing| ***************************************************************************
05:14:19.572- |apero_processing| 
05:14:19.583- |apero_processing| ***************************************************************************
05:14:19.593-@|apero_processing| W[40-503-00019]: Error found for ID='1115'
05:14:19.604-@|apero_processing| 	cal_wave_spirou.py 2019-05-15 -hcfiles 2413185c_pp.fits 2413186c_pp.fits -fpfiles 2413180a_pp.fits 2413181a_pp.fits 2413182a_pp.fits 2413183a_pp.fits 2413184a_pp.fits
05:14:19.614- |apero_processing| ***************************************************************************
05:14:19.624- |apero_processing| 
 E[00-017-00003]: Insufficient number of lines found. 
 	 Found = 0 Required = 200 
 	 Function = science.calib.wave.py.fit_gaussian_triplets()
 E[01-010-00001]: Unhandled error has occurred: Error <class 'apero.locale.core.drs_exceptions.LogExit'> 
 
 Traceback (most recent call last):
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/core/core/drs_startup.py", line 292, in run
    llmain = func(recipe, params)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/recipes/spirou/cal_wave_spirou.py", line 196, in __main__
    hc_e2ds_file, fiber)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 469, in hc_wavesol
    wavell, ampll)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 556, in hc_wavesol_ea
    ampll)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 1693, in fit_gaussian_triplets
    WLOG(params, 'error', TextEntry('00-017-00003', args=eargs))
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/core/core/drs_log.py", line 373, in __call__
    raise drs_exceptions.LogExit(errorstring)
 apero.locale.core.drs_exceptions.LogExit
```

```
05:14:19.636- |apero_processing| 
05:14:19.647- |apero_processing| 
05:14:19.657- |apero_processing| ***************************************************************************
05:14:19.668- |apero_processing| 
05:14:19.679- |apero_processing| ***************************************************************************
05:14:19.689-@|apero_processing| W[40-503-00019]: Error found for ID='1116'
05:14:19.699-@|apero_processing| 	cal_wave_spirou.py 2019-06-15 -hcfiles 2425678c_pp.fits 2425679c_pp.fits -fpfiles 2425671a_pp.fits 2425672a_pp.fits 2425673a_pp.fits 2425674a_pp.fits 2425675a_pp.fits
05:14:19.710- |apero_processing| ***************************************************************************
05:14:19.720- |apero_processing| 
 E[00-017-00003]: Insufficient number of lines found. 
 	 Found = 0 Required = 200 
 	 Function = science.calib.wave.py.fit_gaussian_triplets()
 E[01-010-00001]: Unhandled error has occurred: Error <class 'apero.locale.core.drs_exceptions.LogExit'> 
 
 Traceback (most recent call last):
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/core/core/drs_startup.py", line 292, in run
    llmain = func(recipe, params)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/recipes/spirou/cal_wave_spirou.py", line 196, in __main__
    hc_e2ds_file, fiber)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 469, in hc_wavesol
    wavell, ampll)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 556, in hc_wavesol_ea
    ampll)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 1693, in fit_gaussian_triplets
    WLOG(params, 'error', TextEntry('00-017-00003', args=eargs))
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/core/core/drs_log.py", line 373, in __call__
    raise drs_exceptions.LogExit(errorstring)
 apero.locale.core.drs_exceptions.LogExit
```

```
05:14:19.732- |apero_processing| 
05:14:19.743- |apero_processing| 
05:14:19.754- |apero_processing| ***************************************************************************
05:14:19.764- |apero_processing| 
05:14:19.775- |apero_processing| ***************************************************************************
05:14:19.786-@|apero_processing| W[40-503-00019]: Error found for ID='1117'
05:14:19.796-@|apero_processing| 	cal_wave_spirou.py 2019-06-15 -hcfiles 2425836c_pp.fits 2425837c_pp.fits -fpfiles 2425831a_pp.fits 2425832a_pp.fits 2425833a_pp.fits 2425834a_pp.fits 2425835a_pp.fits
05:14:19.806- |apero_processing| ***************************************************************************
05:14:19.817- |apero_processing| 
 E[00-017-00003]: Insufficient number of lines found. 
 	 Found = 0 Required = 200 
 	 Function = science.calib.wave.py.fit_gaussian_triplets()
 E[01-010-00001]: Unhandled error has occurred: Error <class 'apero.locale.core.drs_exceptions.LogExit'> 
 
 Traceback (most recent call last):
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/core/core/drs_startup.py", line 292, in run
    llmain = func(recipe, params)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/recipes/spirou/cal_wave_spirou.py", line 196, in __main__
    hc_e2ds_file, fiber)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 469, in hc_wavesol
    wavell, ampll)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 556, in hc_wavesol_ea
    ampll)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 1693, in fit_gaussian_triplets
    WLOG(params, 'error', TextEntry('00-017-00003', args=eargs))
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/core/core/drs_log.py", line 373, in __call__
    raise drs_exceptions.LogExit(errorstring)
 apero.locale.core.drs_exceptions.LogExit
```

```
05:14:19.829- |apero_processing| 
05:14:19.839- |apero_processing| 
05:14:19.850- |apero_processing| ***************************************************************************
05:14:19.860- |apero_processing| 
05:14:19.871- |apero_processing| ***************************************************************************
05:14:19.882-@|apero_processing| W[40-503-00019]: Error found for ID='1118'
05:14:19.892-@|apero_processing| 	cal_wave_spirou.py 2019-06-19 -hcfiles 2426398c_pp.fits 2426399c_pp.fits -fpfiles 2426391a_pp.fits 2426392a_pp.fits 2426393a_pp.fits 2426394a_pp.fits 2426395a_pp.fits
05:14:19.902- |apero_processing| ***************************************************************************
05:14:19.913- |apero_processing| 
 E[00-017-00003]: Insufficient number of lines found. 
 	 Found = 0 Required = 200 
 	 Function = science.calib.wave.py.fit_gaussian_triplets()
 E[01-010-00001]: Unhandled error has occurred: Error <class 'apero.locale.core.drs_exceptions.LogExit'> 
 
 Traceback (most recent call last):
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/core/core/drs_startup.py", line 292, in run
    llmain = func(recipe, params)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/recipes/spirou/cal_wave_spirou.py", line 196, in __main__
    hc_e2ds_file, fiber)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 469, in hc_wavesol
    wavell, ampll)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 556, in hc_wavesol_ea
    ampll)
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/science/calib/wave.py", line 1693, in fit_gaussian_triplets
    WLOG(params, 'error', TextEntry('00-017-00003', args=eargs))
  File "/scratch/Projects/spirou/drs/spirou_github/spirou_run/apero/core/core/drs_log.py", line 373, in __call__
    raise drs_exceptions.LogExit(errorstring)
 apero.locale.core.drs_exceptions.LogExit
```

